sudo: required
language: java
cache:
  directories:
    - $HOME/docker
services:
  - docker
before_install:
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar | xargs -I {file} sh -c "docker load -i {file}"; fi
install:
  - docker run --name oracle -d -e ORACLE_ALLOW_REMOTE=true -p 1521:1521 alexeiled/docker-oracle-xe-11g
script:
  - echo 6666
before_cache:
  - mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save -o $HOME/docker/$1.tar $0'