/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_openrasp_plugin_v8_V8 */

#ifndef _Included_com_baidu_openrasp_plugin_v8_V8
#define _Included_com_baidu_openrasp_plugin_v8_V8
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_openrasp_plugin_v8_V8
 * Method:    Initialize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_openrasp_plugin_v8_V8_Initialize
  (JNIEnv *, jclass);

/*
 * Class:     com_baidu_openrasp_plugin_v8_V8
 * Method:    Dispose
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_openrasp_plugin_v8_V8_Dispose
  (JNIEnv *, jclass);

/*
 * Class:     com_baidu_openrasp_plugin_v8_V8
 * Method:    CreateSnapshot
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_openrasp_plugin_v8_V8_CreateSnapshot
  (JNIEnv *, jclass, jstring, jobjectArray);

/*
 * Class:     com_baidu_openrasp_plugin_v8_V8
 * Method:    Check
 * Signature: (Ljava/lang/String;[BI[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_openrasp_plugin_v8_V8_Check__Ljava_lang_String_2_3BI_3BI
  (JNIEnv *, jclass, jstring, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_baidu_openrasp_plugin_v8_V8
 * Method:    Check
 * Signature: (Ljava/lang/String;[BILcom/baidu/openrasp/plugin/v8/Context;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_openrasp_plugin_v8_V8_Check__Ljava_lang_String_2_3BILcom_baidu_openrasp_plugin_v8_Context_2Z
  (JNIEnv *, jclass, jstring, jbyteArray, jint, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
